builders:
  resourceBuilder:
    target: resourceBuilder
    import: "package:flutter_resources/flutter_resources.dart"
    builder_factories: ["resourceBuilder"]
    build_extensions: {'.fr':['.res.dart']}
    auto_apply: root_package
    build_to: source